In [1]:
import numpy as np

In [3]:
a=[1,2,3]

In [5]:
type(a)

list

In [7]:
array=np.array(a)

In [13]:
array.dtype

dtype('int32')

ndarray를 편라하게 생성하기-arange,zeros,ones

In [20]:
sequence_array=np.arange(10)
print(sequence_array)
print(sequence_array.dtype,sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [21]:
zero_array=np.zeros((3,2),dtype="int32")
print(zero_array)
print(zero_array.dtype,zero_array.shape)

one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype,one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


ndarray의 차원과 크기를 변경하는 reshape

In [25]:
array1=np.arange(10)
print("array1:\n",array1)

array2=array1.reshape(2,5)
print("array:\n",array2)

array3=array1.reshape(5,2)
print("array:\n",array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [26]:
arraý.reshape(4,3)

NameError: name 'arraý' is not defined

In [29]:
array=np.arange(10)
print(array1)
array2=array1.reshape(-1,5)
print("array2 shape",array2.shape)
array3=array.reshape(5,-1)
print("array3 shape",array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape (2, 5)
array3 shape (5, 2)


In [34]:
array1=np.arange(8)
array3d=array1.reshape((2,2,2))
print("array3d:\n",array3d.tolist())

array5=array3d.reshape(-1,1)
print("array5:\n",array5.tolist())
print("array5 shape:",array5.shape)

array6=array1.reshape(-1,1)
print("array6:\n",array6.tolist())
print("array6 shape:",array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


넘파이의 ndarray의 데이터 세트 선택하기-인덱싱

단일값 추출

In [40]:
array1=np.arange(start=1,stop=10)
print("array1:",array1)

value=array1[2]
print("value:",value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [41]:
print("맨 뒤의 값:",array1[-1],"맨 뒤에서 두번째 값:",array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두번째 값: 8


In [44]:
array1[0]=9
array1[8]=0
print("array1:",array1)

array1: [9 2 3 4 5 6 7 8 0]


In [46]:
array1d=np.arange(1,10)
array2d=array1d.reshape(3,3)
print(array2d)

print("(row=0,col=0 index가리키는 값:",array2d[0,0])
print("(row=0,col=1 index가리키는 값:",array2d[0,1])
print("(row=1,col=0 index가리키는 값:",array2d[1,0])
print("(row=2,col=2 index가리키는 값:",array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0 index가리키는 값: 1
(row=0,col=1 index가리키는 값: 2
(row=1,col=0 index가리키는 값: 4
(row=2,col=2 index가리키는 값: 9


In [49]:
array1=np.arange(start=1,stop=10)
array3=array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


슬라이싱

In [53]:
array1=np.arange(1,10)
array4=array1[:3]

array1=np.arange(1,10)
array4=array1[:3]
print(array4)

array5=array1[3:]
print(array5)

array6=array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [63]:
array1d=np.arange(1,10)
array2d=array1d.reshape(3,3)
print("array2d:\n",array2d)

print('array2d[0:2,0:2]\n',array2d[0:2,0:2])
print('array2d[1:3,0:3]\n',array2d[1:3,0:3])
print('array2d[1:3,:]\n',array2d[1:3,:])
print('array2d[:,:]\n',array2d[:,:])
print('array2d[:2,1:]\n',array2d[:2,1:])
print('array2d[:2,0]\n',array2d[:2,0])






array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2]
 [[1 2]
 [4 5]]
array2d[1:3,0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3,:]
 [[4 5 6]
 [7 8 9]]
array2d[:,:]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,1:]
 [[2 3]
 [5 6]]
array2d[:2,0]
 [1 4]


In [67]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:',array2d[0].shape
,"array2d[1] shape:",array2d[1].shape)



[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


팬시 인덱싱

In [74]:
array1d=np.arange(1,10)
array2d=array1d.reshape(3,3)
print(array2d)

array3=array2d[[0,1],2]
print('array2d[0,1],2=>',array3.tolist())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0,1],2=> [3, 6]


불린 인덱싱

In [78]:
array1d=np.arange(1,10)
array3=array1d[array1d>5]
print('array1d>5 불린 인덱싱 결과 값:',array3)

array1d>5 불린 인덱싱 결과 값: [6 7 8 9]


In [79]:
array1d>5

array([False, False, False, False, False,  True,  True,  True,  True])

행렬의 정렬

In [89]:
org_array=np.array([3,1,9,5])
print('원본 행렬:',org_array)
sort_array1=np.sort(org_array)
print('np.sort()호출 후 반환된 정렬 행렬:',sort_array1)

원본 행렬: [3 1 9 5]
np.sort()호출 후 반환된 정렬 행렬: [1 3 5 9]


In [90]:
print('np.sort()호출 후 원본 행렬:',org_array)
sort_array2=org_array.sort()
print('org.array.sort()호출 후 반환된 행렬:',sort_array2)
print('org.array.sort()호출 후 원본 행렬:',org_array)

np.sort()호출 후 원본 행렬: [3 1 9 5]
org.array.sort()호출 후 반환된 행렬: None
org.array.sort()호출 후 원본 행렬: [1 3 5 9]


In [92]:
sort_array1_desc=np.sort(org_array)[::-1]
print('내림차순으로 정렬:',sort_array1_desc
)


내림차순으로 정렬: [9 5 3 1]


4 판다스

In [93]:
import pandas as pd

In [ ]:
print('test2')